In [1]:
from sklearn import preprocessing
import numpy as np

import matplotlib.pyplot as plt
import scipy.stats as stats
import matplotlib.mlab as mlab
from scipy.stats import norm
import seaborn as sns
import plotly.express as px

from datetime import datetime
import pandas as pd

In [2]:
with open('SampleInput.txt') as f:
    data = f.readlines()

In [8]:
columns = ['Year','Day','Hour','Minutes','Seconds','Milliseconds','unknown']
rows = []
for i in data:
    if 'DTG' in i:
        columns.append(i.replace('\n',''))
    elif len(i.split(" "))>5:
        new_list = [j for j in i.split(" ") if j not in ['',0,'\n']]

        date_string = str(new_list[1]) + " " +  str(new_list[0]) + " " +  str(new_list[2]) + " " +  str(new_list[3]) + " " +  str(new_list[4]) + " " +  str(new_list[5])
        date_object = datetime.strptime(date_string, "%j %Y %H %M %S %f")
        new_list = new_list[6:]
        date_str = date_object.strftime("%Y-%m-%d")
        new_list.insert(0, date_str)
        
        
        if new_list[14] == 'ON':
            new_list[14] = 1
        else:
            new_list[14] = 0
            
        if new_list[15] == 'ON':
            new_list[15] = 1
        else:
            new_list[15] = 0
        
        if new_list[16] == 'ON':
            new_list[16] = 1
        else:
            new_list[16] = 0
            
        if new_list[17] == 'SYNC':
            new_list[17] = 1
        else:
            new_list[17] = 0
            
        if new_list[18] == 'NOT_USBL':
            new_list[18] = 0
        else:
            new_list[18] = 1
            
        if new_list[19] == 'ENA':
            new_list[19] = 1
        else:
            new_list[19] = 0
        
        if new_list[20] == 'LOW':
            new_list[20] = 0
        else:
            new_list[20] = 1
            
        if new_list[21] == 'ON':
            new_list[21] = 1
        else:
            new_list[21] = 0
            
        if new_list[22] == 'SYNC':
            new_list[22] = 1
        else:
            new_list[22] = 0
            
            
        rows.append(new_list)

In [9]:
columns = ['Date']+columns[6:]

In [10]:
import pandas as pd
df = pd.DataFrame()

In [11]:
for j in range(len(columns)):
    col_data = []
    for i in rows:        
        if j >= 1:
            col_data.append(float(i[j]))
        else: 
            col_data.append(i[j])
    df[columns[j]] = col_data
    
display(df)

,Date,unknown,DTG-1_PCH_ANALOG_RAT (Analog),DTG-1_ROL_ANALOG_RAT (Analog),DTG-1_PCH_FINE_RATE (Analog),DTG-1_ROL_FINE_RATE (Analog),DTG-2_YAW_ANALOG_RAT (Analog),DTG-2_PCH_ANALOG_RAT (Analog),DTG-2_YAW_FINE_RATE (Analog),DTG-2_PCH_FINE_RATE (Analog),...,DTG-2_ELECTRONICS_TH (Analog),DTG-2_SYNC_STS (Digital),DTG-2_ON_STS (Digital),DTG-1_ON_STS (Digital),DTG-2_RB_SUPPLY_STS (Digital),DTG-1_SYNC_STS (Digital),DTG-3_USBL_STS (Digital),DTG_ANALOG_RATE_CHK (Digital),DTG-2_TEMP_SEL_CMD_S (Digital),DTG-1_RB_SUPPLY_STS (Digital)
0,2018-04-15,22.0,-0.0469,-0.0385,0.00542,0.01121,0.1294,-0.0687,0.00695,0.00769,...,52.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
1,2018-04-15,23.0,-0.0469,-0.0385,0.00542,0.01121,0.1294,-0.0687,0.00690,0.00769,...,52.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
2,2018-04-15,26.0,-0.0469,-0.0385,0.00542,0.01121,0.1294,-0.0687,0.00690,0.00769,...,52.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
3,2018-04-15,29.0,-0.0469,-0.0385,0.00542,0.01121,0.1294,-0.0687,0.00690,0.00769,...,52.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
4,2018-04-15,4.0,-0.0469,-0.0385,0.00542,0.01121,0.1294,-0.0687,0.00690,0.00769,...,52.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186293,2018-05-18,22.0,-0.0469,-0.0385,0.00577,0.01131,-0.0981,-0.0687,0.00646,0.00799,...,51.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
186294,2018-05-18,23.0,-0.0469,-0.0385,0.00582,0.01131,-0.0981,-0.0687,0.00651,0.00804,...,51.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
186295,2018-05-18,26.0,-0.0469,-0.0385,0.00582,0.01131,-0.0981,-0.0687,0.00651,0.00804,...,51.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
186296,2018-05-18,29.0,-0.0469,-0.0385,0.00582,0.01131,-0.0981,-0.0687,0.00651,0.00804,...,51.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
186297,2018-05-18,4.0,-0.0469,-0.0385,0.00582,0.01131,-0.0981,-0.0687,0.00651,0.00804,...,51.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0

In [12]:
df2 = df.groupby(['Date'])['Date'].count()
with pd.option_context('display.max_rows', None, 'display.max_columns', None):  # more options can be specified also
    print(df2)

Date
2018-04-15     1109
2018-04-16     5885
2018-04-17     5503
2018-04-18     5969
2018-04-19     5318
2018-04-20     5233
2018-04-21     4969
2018-04-22     6930
2018-04-23     5816
2018-04-24     4111
2018-04-25     4841
2018-04-26     5618
2018-04-27     5216
2018-04-28     4232
2018-04-29     5685
2018-04-30     4905
2018-05-01     5814
2018-05-02     6070
2018-05-03     5477
2018-05-04     4991
2018-05-05     5675
2018-05-06     5130
2018-05-07     5018
2018-05-08     5735
2018-05-09     5409
2018-05-10     8878
2018-05-11    10203
2018-05-12     5418
2018-05-13     5412
2018-05-14     5262
2018-05-15     5952
2018-05-16     5895
2018-05-17     5406
2018-05-18     3213
Name: Date, dtype: int64